### ISSUE TITLE
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMessageBox'

### ISSUE THREAD

**Issue by bavario-lginc** [FroggoTheDoggo29/pyKCLCreate#2]
When I try to save a kcl file, I get this error, and the program closes:
![grafik](https://user-images.githubusercontent.com/35093969/132325093-fa258b0f-190b-4b07-86a4-810446c8ac69.png)
Tested that with UFOShapePassThroughPlanet converted to obj with Blender.
I'm using Python 3.9 and PyQt5 Version 5.15.

Does someone know why that would happen?

**Comment by gayfrogog** [comment]
It crashes here. I seem to have left a few PyQt4 commands in accidentally. But essentially, your model has too many vertices. It needs to be under 65535 vertices.
```py
    def onGeometryOverflow(self,error):
        message = QtGui.QMessageBox(self)
        message.setIcon(QtGui.QMessageBox.Critical)
        message.setText('GeometryOverflowError: {}.'.format(error))
        message.setInformativeText('Try reducing the number of triangles in the model.')
        message.setStandardButtons(QtGui.QMessageBox.Ok)
        message.setDefaultButton(QtGui.QMessageBox.Ok)
        message.exec_()
```

EDIT: Made a mistake, your model needs to have less than ~16k triangles. I don't know the exact number off the top of my head.

**Comment by bavario-lginc** [comment]
Hmm, ok. I tried using the actual kcl converted to obj this time, but that still caused an error, namely this:
![grafik](https://user-images.githubusercontent.com/35093969/134144136-bf8b942d-dd95-47d0-9220-84d1f1b09856.png)
Is there a specific reason that it shouldn't have permission?

Edit: I fixed it by running the bat file as admin.
